### ISSUE TITLE
why i cant turn on bot?

### ISSUE THREAD

**Issue by ajb3296** [revoltchat/revolt.py#11]
**Describe the bug**

i cant turn on bot with screenshot's msg

**To Reproduce**
A small code snippet showing the error

```py
import asyncio
import aiohttp
from bot import TOKEN, commandInt

import revolt


class Client(revolt.Client):
    async def on_message(self, message: revolt.Message):
        msg = None
        if message.content[0] == commandInt:
            msg = message.content[1:]
        if msg == "hello":
            await message.channel.send("wow")

async def main():
    async with aiohttp.ClientSession() as session:
        client = Client(session, TOKEN)
        await client.start()

asyncio.run(main())
```

**Expected behavior**

**Screenshots**

![스크린샷 2021-09-03 오후 2 03 49](https://user-images.githubusercontent.com/33373557/131953138-b1400ad8-929d-4b5f-a823-b2ad9e2c82dd.png)

**Library version**
Access this info via `pip show revolt.py`

latest(download from github)

**Additional context**

**Comment by Zomatree** [comment]
Can you explain what isnt working?

**Comment by ajb3296** [comment]
it just repeats the message "Sending heartbeat" and the bot doesn't turn on.
i dont know what is problem

**Comment by mtlhdnrd** [comment]
did you give it a token? did you add the bot to any servers?

**Comment by Zomatree** [comment]
Closing from inactivity, if you continue to have this issue please re-open this issue.
