### ISSUE TITLE
Error while starting

### ISSUE THREAD

**Issue by RawW-wq** [revoltchat/revolt.py#15]
When i try to start my bot with the code from the git I'm getting this error.
![image](https://user-images.githubusercontent.com/76211975/133282131-53f7e487-ef69-457a-9d9c-8ef03c5dc13d.png)

**Comment by Dark42ed** [comment]
@RawW-wq Can you show us the code you wrote?

**Comment by wompking** [comment]
I also have this problem; I've written a file containing _only_ `import revolt` and it produces this error when ran with `python3`.

**Comment by Zomatree** [comment]
Closing from inactivity, if you continue to have this issue please re-open this issue.
