### ISSUE TITLE
Module revolt.py not found in repl.it

### ISSUE THREAD

**Issue by FanMclaine** [revoltchat/revolt.py#27]
https://media.discordapp.net/attachments/731118648126603274/948144352146898954/unknown.png?width=501&height=417

**Comment by RGBCube** [comment]
make a `.replit` file in your repl, and paste this to it:
```
language="python3"
run = """
pip install revolt.py
python main.py
"""

[packager]
ignoredPackages=["revolt.py", "revolt"]
```
should work.

**Comment by Zomatree** [comment]
Repl.it uses Python 3.8 while revolt.py requires 3.9+.
