### ISSUE TITLE
Example Bot is not working

### ISSUE THREAD

**Issue by martinbndr** [revoltchat/revolt.py#29]
**Describe the bug**
The default Bot example does not work. I installed everything like it has to be

**To Reproduce**
- create a virtualenv
- install revolt.py
- paste in the example Bot
- Start the bot

**Expected behavior**
!hello should force the bot to respond with "hi how are you"

**Screenshots**
![image](https://user-images.githubusercontent.com/55140357/157309440-9cb3266c-1ef5-4e58-93b1-d65d1ec80639.png)

Error:
```
python.exe c:/Users/MB/Documents/PythonBots/revoltchat/test/main.py
Task exception was never retrieved
future: <Task finished name='Task-15' coro=<Client.on_message() done, defined at c:\Users\MB\Documents\PythonBots\revoltchat\test\main.py:6> exception=TypeError("object str can't be used in 'await' expression")>
Traceback (most recent call last):
  File "c:\Users\MB\Documents\PythonBots\revoltchat\test\main.py", line 8, in on_message
    await message.channel.send("hi how are you")
  File "C:\Users\MB\Documents\PythonBots\revoltchat\test\env\lib\site-packages\revolt\messageable.py", line 60, in send   
    message = await self.state.http.send_message(await self._get_channel_id(), content, embed_payload, attachments, reply_payload, masquerade_payload)
TypeError: object str can't be used in 'await' expression
```

**Library version**
Access this info via `pip show revolt.py`
0.1.6

**Additional context**

**Comment by justamirror** [comment]
hey this isnt a unconfirmed bug, in fact its because its awaiting the _get_channel_id function, which on the channel is NOT async

**Comment by justamirror** [comment]
about this issue, its the same here, and i checked. somehow the "_get_channel_id" prop of the TextChannel is not a async function

 message = await self.state.http.send_message(_**await self._get_channel_id()**_, content, embed_payload, attachments, reply_payload, masquerade_payload)

**Comment by justamirror** [comment]
why does it use that anyway????? the _get_channel_id() function just returns self.id

**Comment by Zomatree** [comment]
This is fixed on master already.

**Comment by justamirror** [comment]
no it isnt?????
i literally JUST tried to update and its alllll up to date

**Comment by justamirror** [comment]
unless my pip is being nuts

**Comment by justamirror** [comment]
ru SURE you pushed the change to pip

**Comment by Zomatree** [comment]
This is fixed on revolt.py@master, Its not in a release or on PyPi yet.
