### ISSUE TITLE
Message.edit() does not let you use None to clear a message's content

### ISSUE THREAD

**Issue by MysticMia** [revoltchat/revolt.py#57]
**Describe the bug**
Unlike member.edit() where you can reset someone's username by passing None, you can't clear a message's content by editing it using None.

**To Reproduce**
```py
await message.edit(content=None, embeds=embed)
```

**Expected behavior**
Expected message content to clear. This did not happen, however.

**Library version**
0.1.11

**Additional context**
This is likely caused by the following code:
```py
def edit_message(self, channel: str, message: str, content: Optional[str], embeds: Optional[list[SendableEmbedPayload]] = None) -> Request[None]:
    json = {}

    if content is not None:
        json["content"] = content
```
Instead of setting the default to and checking for revolt.utils.Missing, it sets/checks it None. This means you can't un-set something by passing the None argument because it'll be filtered out as 'default' argument.

**Comment by MysticMia** [comment]
It works if you pass `""` (an empty string) for the message content, instead of None.

**Comment by Zomatree** [comment]
You cant pass `None` to clear the content, the Revolt API does not support that.
