### ISSUE TITLE
how to join to voice channel

### ISSUE THREAD

**Issue by SachaTending** [revoltchat/revolt.py#58]
im trying to create music bot on python and i have issue
how to connect to voice channel, or how to get voicechannel object
in discord.py i can just do this: ctx.author.voice

**Comment by MysticMia** [comment]
Voice support is not yet supported by Revolt bots. You can only join voice channels, but not leave them or do anything with voice, unfortunately. Zomatree said: "I plan to add it when the voice rewrite is a bit more stable. I don't want to add support for voice and then need to rewrite it all after a couple months", in the #Help channel of the Revolt.py support server.
