### ISSUE TITLE
🐛  Import error due to http import

### ISSUE THREAD

**Issue by mraniki** [revoltchat/revolt.py#66]
../../../miniconda3/envs/dev311/lib/python3.11/site-packages/revolt/__init__.py:5: in <module>
    from .client import *
../../../miniconda3/envs/dev311/lib/python3.11/site-packages/revolt/client.py:11: in <module>
    from .http import HttpClient
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    from __future__ import annotations
    
    from typing import (TYPE_CHECKING, Any, Coroutine, Literal, Optional, TypeVar,
                        Union, overload)
    
    import aiohttp
    import ulid
    
>   from .errors import Forbidden, HTTPError, ServerError
E   ImportError: cannot import name 'Forbidden' from 'revolt.errors' (/Users/eridu/miniconda3/envs/dev311/lib/python3.11/site-packages/revolt/errors/__init__.py)

../../../miniconda3/envs/dev311/lib/python3.11/site-packages/revolt/http.py:9: ImportError

http.py seems to not be importing the RevoltError which might be the issue.

**Comment by Zomatree** [comment]
How did you install revolt.py?

**Comment by mraniki** [comment]
Installed via pip and trying the example. The venv is on 311

**Comment by Zomatree** [comment]
What command did you run to install revolt.py?

**Comment by mraniki** [comment]
pip install 'revolt.py'
