### ISSUE TITLE
Rename the package

### ISSUE THREAD

**Issue by andreas-hartmann** [revoltchat/revolt.py#81]
**Describe the bug**
Naming the package "python.py" causes warnings downstream. Linting tools complain that the import "revolt" is coming from a different package. Using an alias doesn't work because "revolt.py" contains a period.

**To Reproduce**
`import revolt` in PyCharm for instance with `revolt.py==0.2.0` in requirements.txt will cause a warning.

**Expected behavior**
The package should have a standards-compliant name, such as revoltpy or something.
No warnings should be produced.

**Comment by Zomatree** [comment]
This is an issue with the tools that require the names to match, it is not required that the package name must match the library name.

This is not something I will change.
