### ISSUE TITLE
aiohttp bump in version

### ISSUE THREAD

**Issue by JDJGInc** [revoltchat/revolt.py#82]
I get an aiohttp warning on the project asking for 3.10.2 or higher due to a possible security problem.
This is why I am requesting to update it.

This appears to only happen on servers as it mentions it in:

"In aiohttp, compressed files as symlinks are not protected from path traversal"

But this is better to be bumped if possible.

lastest git version.

**Comment by JDJGInc** [comment]
the image version:
![image](https://github.com/user-attachments/assets/99c163eb-a8cb-4b08-82bb-88ad5828dcdf)

**Comment by stafsa** [comment]
which os are you using?
