### ISSUE TITLE
Support persistent member mention after member leaves guild. (member.id.user)

### ISSUE THREAD

**Issue by BoQsc** [revoltchat/revolt.py#87]
**Describe the bug**
As you might know, after a guild member **leaves your guild**; and you **refresh your web browser**, you are **left with nothing but a weird mention handle**.
![Image](https://github.com/user-attachments/assets/ceaec7bb-cc66-452f-aded-d07d1bbb3a5e)

To resolve this, on **revolt.js project** we would use [`member.id.user`](https://revolt.js.org/classes/ServerMember.html#id):
```
await targetChannel.sendMessage("<@" + member.id.user + ">" + `Left the server.`);
```
![Image](https://github.com/user-attachments/assets/c8059fad-b014-465b-9fda-6a7cbc3dd5ab)

However `member.id.user` is clearly not existant in **revolt.py** and I wonder how to achieve the same result here.

**Comment by Zomatree** [comment]
The user id is used in both libraries and are the exact same, it depends on whether the user's client has the user cached or not, if there is no shared servers or relationship then they won't them cached, this is not something which can be changed library side, the same would happen in revolt.js as well if they are no longer cached.

**Comment by BoQsc** [comment]
@Zomatree Have you tested the suggested code line in a revolt.js project?

> await targetChannel.sendMessage("<@" + member.id.user + ">" + `Left the server.`);

**Comment by Zomatree** [comment]
The ID is the exact same, the user ID is used in both.

**Comment by BoQsc** [comment]
@Zomatree No, I only asked you to answer if you tested it yourself or not. I'm aware of what you are saying. I seem to be getting different results than what you are explaining.

**Comment by Zomatree** [comment]
This is dependant on the clients cache not anything to do with the library, I cannot control it nor can revolt.js
