### ISSUE TITLE
revolt.py: MemberCompositeKey id's user reference is not being cached on Revite (Revolt Web Client )

### ISSUE THREAD

**Issue by BoQsc** [revoltchat/revolt.py#88]
Posting this and closing, since the author of revolt.py refuse to investigate, but also locked/limited the conversation. https://github.com/revoltchat/revolt.py/issues/87

**Comment by IAmTomahawkx** [comment]
You were provided a reason for the logic. Locking of a conversation does not mean to create a new thread, it is a very subtle hint to drop the conversation.
